[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
hexxy32 = { path = "../hexxy32" }

[profile.dev]

[profile.release]
panic = "abort"
# values: 2, 3, s, z
opt-level = 3
overflow-checks = false
lto = true
