[package]
name = "bad_apple"
version = "0.1.0"
edition = "2021"

[dependencies]
hexxy32 = { path = "../hexxy32" }
include_bytes_aligned = "0.1.4"

[profile.release]
panic = "abort"
# values: 2, 3, s, z
opt-level = 3
overflow-checks = false
lto = true
