[package]
name = "hexxy32"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii = { version = "1.1", default-features = false }

[profile.dev]

[profile.release]
panic = "abort"
opt-level = "z"
overflow-checks = false
lto = true
